### ISSUE TITLE
invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by BolletuH** [hashicorp/vagrant-vmware-desktop#105]
### Actual behavior - 
Computer has been having issues lately and suspect a corrupted file somewhere. Have attempted to uninstall and reinstall Vagrant, the Vagrant VMWare Utility, & VMWare itself. All versions have been upgraded to the latest. Not sure what is going on, but unable to interact with VMWare through Vagrant.

**Note:** Service for Vagrant utility will not start.

Vagrant encountered an unexpected communications error with the

Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please open a new issue at:

  https://github.com/hashicorp/vagrant-vmware-desktop/issues

Event Viewer: vagrant-vmware-utility service setup failed: invalid character '\x00' looking for beginning of value

[utility.log](https://github.com/hashicorp/vagrant-vmware-desktop/files/12831447/utility.log)

**Comment by Lazza** [comment]
I had the same issue today and solved it by removing corrupted configuration files. **I deleted the following folder:**

    C:\ProgramData\hashicorp\vagrant-vmware-desktop\settings
