### ISSUE TITLE
Unable to start machine if $VAGRANT_HOME is set

### ISSUE THREAD

**Issue by nameless66** [hashicorp/vagrant-vmware-desktop#110]
Hey there,

when I set $VAGRANT_HOME on a Mac System (OSX Sonoma) to a specific folder, which is not synced by icloud, I couldn't start  a machine.

**Error Message**
No usable default provider could be found for your system.
...

Does someone know a workaround?

Thanks in Advance!

**Comment by chrisroberts** [comment]
Hi there,

Vagrant stores multiple things within `VAGRANT_HOME`, and one of those things is plugins that have been installed. After you update the location of `VAGRANT_HOME`, you'll then need to install the plugins you want to use (in this case: `vagrant plugin install vagrant-vmware-desktop`).
