### ISSUE TITLE
Access to the release documentation in the Vagrant confluence page

### ISSUE THREAD

**Issue by rit001** [hashicorp/vagrant-vmware-desktop#21]
While the confluence page is referenced in the README.md text it does not seem to be published as a public page and so can not be accessed.

As I can not access the page I have no way to tell if it holds important info.

Thanks

**Comment by chrisroberts** [comment]
Resolved in https://github.com/hashicorp/vagrant-vmware-desktop/commit/e8939be0818c6be5b7ed1fe1df311465f0a03885
