### ISSUE TITLE
Vagrant vmware provider fails to work with Fusion Tech Preview

### ISSUE THREAD

**Issue by fatso83** [hashicorp/vagrant-vmware-desktop#22]
Hi, I am running an Apple Silicon Macbook (ARM) and found out that VirtualBox does not work on that platform. I then learned that VMWare released a Tech Preview of Fusion for ARM last month, and so I was hopeful in getting that to work with Vagrant, as you provide a VMWare provider.

I followed all the steps for installing the provider and you can see from the output that it seems to work. I then proceeded to follow the Getting Started guide (skipping the install of VirtualBox). You could also see my [own notes](https://gist.github.com/fatso83/49980bbf065022d36c3a42369479a8df) when doing this. All seemed fine up until the last steps:

```
$ vagrant init hashicorp/bionic64

$ vagrant up --provider vmware_desktop
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please contact support@hashicorp.com
```

When running with the debug output, it seems as if it could not find any image matching the supplied image. I am not that familiar with Vagrant, but I assumed it might have to do with the image needing to specifically work with VMWare? So I searched vagrant images for anything support vmware and tried both `"generic/ubuntu2104"` and `"roboxes/ubuntu2104"` which both were tagged vmware. No luck there either; they all erred with something like this in the debug output

```
 WARN vagrantfile: Performing lookup with initial values roboxes/ubuntu2104 with version
 INFO box_collection: Box not found: roboxes/ubuntu2104 (vmware_desktop, vmware_fusion, vmware_workstation)
```

The following is info following the Bug template

```
$ vagrant -v
Vagrant 2.2.18

carlerik at carl-eriks-air in ~/dev/dotfiles (master)
$ vagrant plugin list
vagrant-vmware-desktop (3.0.1, global)
  - Version Constraint: > 0

carlerik at carl-eriks-air in ~/dev/dotfiles (master)
$ /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility -v
1.0.20

carlerik at carl-eriks-air in ~/dev/dotfiles (master)
$ uname -a
Darwin carl-eriks-air.lan 21.1.0 Darwin Kernel Version 21.1.0: Sat Sep 11 12:27:45 PDT 2021; root:xnu-8019.40.67.171.4~1/RELEASE_ARM64_T8101 arm64
```

### Debug output

https://gist.github.com/fatso83/7da6c48debb4b48333feab90b44964d8

### Expected behavior

That it fired up a vm as described in getting started

### Actual behavior

It erred with
```
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver.
```

### Steps to reproduce

1. Use a M1 Mac (arm)
1. Install the Fusion Tech Preview
1. vagrant init hashicorp/bionic64
1. vagrant up --provider vmware_desktop

**Comment by sbailliez** [comment]
@chrisroberts Just started on this today and got it to work with the box you posted. Thank you! I did not do much yet but `vagrant ssh` and look around in the box but hope to dig more in the next few days as I will be trying to move an existing virtualbox environment to vmware on m1 pro.

Big thank you as well to all previous contributors to this issue @fatso83 @caius @yyounes75 who saved me a huge amount of time.

**Comment by fatso83** [comment]
@chrisroberts I am not that well versed in the Vagrantverse, so I was unsure of what this referenced:
>  the reason the networking is failing is due to the predictable network interface names being used

Some searching led me to [this gist talking](https://gist.github.com/brbsix/b70413dec907906ef659#to-disable-this-behavior) about just this:

> Starting with v197 systemd/udev will automatically assign predictable, stable network interface names for all local Ethernet, WLAN and WWAN interfaces. This is a departure from the traditional interface naming scheme ("eth0", "eth1", "wlan0", ...), but should fix real problems.
> 
> http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

This is what you are talking about, right? If so, I should be able to do the changes mentioned there and upload a new patched version of my existing image.

**Comment by fatso83** [comment]
Seems like the bento templates take this into account: https://github.com/chef/bento/pull/1014/files

I will try and fix the current image. If time permits (not likely), it would be nice to supply a new PR for the bento project so that they have an ARM template as well.

**Comment by chrisroberts** [comment]
@fatso83 Yes, [that](http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) is what I was referencing, and the bento PR you have linked includes the required GRUB modifications.

I'm still investigating the linked clone part as I'm still experiencing that failure.

**Comment by sbailliez** [comment]
@fatso83 here are part of the notes I wrote down this weekend with all the steps: https://gist.github.com/sbailliez/f22db6434ac84eccb6d3c8833c85ad92 - Let me know if something is confusing, missing or incorrect.

**Comment by ralfkrause** [comment]
As already mentioned above the network problems are really related to the predictable network interface names.
As soon as I was falling back to the classic naming convention (eg. eth0) network worked perfectly.

I've uploaded two boxes for the VMware provider:

[Ubuntu Server 20.04](https://app.vagrantup.com/rkrause/boxes/ubuntu-20.04-arm64)
[Ubuntu Server 21.10](https://app.vagrantup.com/rkrause/boxes/ubuntu-21.10-arm64)

I tested several vagrant configurations and everything seems to work.

**Comment by neuraload** [comment]
Hello. Any new updates on this ? I am still having issues. Thank you.

Using box: https://app.vagrantup.com/rkrause/boxes/ubuntu-20.04-arm64

➜  Vagrant  /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility -v
1.0.21

INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f8deb09edb0>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<HashiCorp::VagrantVMwareDesktop::Errors::DriverAPIRequestUnexpectedError: Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please contact support@hashicorp.com>
ERROR vagrant: Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command

**Comment by fatso83** [comment]
@neuraload Kind of hard to help you when you don't supply a reproducible test case. You could be missing any number of steps. Have you followed @sbailliez [gist instructions](https://gist.github.com/sbailliez/f22db6434ac84eccb6d3c8833c85ad92) to the letter?

**Comment by neuraload** [comment]
@fatso83 Sorry for not providing additional information. Yes, I followed @sbailliez gist instructions and it doesn't work.

If there is any info I can provide please let me know.

**Comment by fatso83** [comment]
@neuraload I guess creating a StackOverflow question (and posting the link here) where you detail all the steps involved, including verifying what works at which stage, would give you the best chances of getting some help finding out. As you can see from this thread, there are many steps along the way where we get valuable diagnostic output. To me, it is unclear at which step you get problems and which of the steps were successful and not. I don't think I can help, as I don't use Vagrant (apart from this experiment, which was valuable in itself), but others (especially on SO) will have different incentives.

I will close this issue, as the provider _does_ work with VMWare Fusion Tech Preview on ARM, but it does not work all that great from a user perspective. I think some issues/feature requests that should exist would be:
- The provider should detect that VMWare is not installed and explicitly tell the user in cleartext
- The provider should detect that VMWare fails to boot the image (this will happen on all non-ARM images, i.e. 99%)

**Comment by bmalli91** [comment]
Hi, 

Getting the following error. I wonder if anyone of you could assist me to install vagrant in my M1 machine.


Thanks in advance

**Comment by fatso83** [comment]
> Getting the following error. I wonder if anyone of you could assist me to install vagrant in my M1 machine

There is way too little reproduction info here to help you out. You don't even list what you have tried, like the commands and what you have tried after googling a bit. AFAIK, Vagrant recommends you download their binaries anyhow, so try that first. And GitHub really is not the place for issues like this. Try SuperUser or some some Homebrew forum.
