### ISSUE TITLE
Enhancement Request: Env variable to override default install path

### ISSUE THREAD

**Issue by fatso83** [hashicorp/vagrant-vmware-desktop#25]
**Is your feature request related to a problem? Please describe.**
From issue #22 it seems like the vmware provider is unable to find the vmware fusion install when it is installed in non-standard locations. It is only when you move it to `/Application/VMWare Fusion.app` that it can find the files. As the Tech Preview installs itself under a different path, this means official fusion versions do not work without manually renaming the application. This of course also makes it hard to test out different versions of vmware that might be installed at the same time.

**Describe the solution you'd like**
Support an environment variable for overriding the location the provider will try and look up the vmware files. Something like
`export VAGRANT_VMWARE_INSTALL_DIR="/Applications/VMWare Fusion Tech Preview.app"`.

**Describe alternatives you've considered**
As described in https://github.com/hashicorp/vagrant-vmware-desktop/issues/22#issuecomment-952819799, one can manually rename the version currently installed at the default location and then make symlinks:
```
ln -s /Applications/VMWare\ Fusion\ Tech\ Preview.app /Applications/VMWare\ Fusion.app
```
That's a bit of a chore, though.

**Additional context**
See #22.

**Comment by chrisroberts** [comment]
Adding the info to the VMware provider FAQ docs: https://github.com/hashicorp/vagrant/pull/12566
