### ISSUE TITLE
Release documentation is not public

### ISSUE THREAD

**Issue by fatso83** [hashicorp/vagrant-vmware-desktop#26]
The bottom of the README.md file for this project says 
> See the release documentation in the [Vagrant confluence page](https://hashicorp.atlassian.net/wiki/spaces/vagrant/pages/1039532466/Vagrant+VMware)

and has a link to https://hashicorp.atlassian.net/wiki/spaces/vagrant/pages/1039532466/Vagrant+VMware. That Confluence space is not open to public, demanding authorization, and so it has no place on a public open source project, unless that space is either opened up for public or the docs are moved/copied into some public wiki.

**Comment by chrisroberts** [comment]
Duplicate of #21
