### ISSUE TITLE
Shared folders are not mounted unless gui is set to true

### ISSUE THREAD

**Issue by scalp42** [hashicorp/vagrant-vmware-desktop#33]
### Vagrant version

```
Vagrant 2.2.19
```

### Vagrant VMware plugin version

```
vagrant-vmware-desktop (3.0.1, global)
  - Version Constraint: > 0
```

### Vagrant VMware utility version

```
1.0.21
```

### Host operating system

```
macOS Montery 12.0.1
```

### Guest operating system

```
Ubuntu 20.04 focal arm64 
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "axnetlabs/axnetlabs_focal_arm64"
  c.vm.box_check_update = true
  c.vm.hostname = "default-ubuntu-1804.vagrantup.com"
  c.ssh.insert_key = false
  c.vm.network(:private_network, {:type=>"dhcp"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/scalp/.aws", "/root/.aws", disabled: false, owner: 'root', group: 'root'
  c.vm.synced_folder "/Users/scalp/.aws", "/home/vagrant/.aws", disabled: false, owner: 'vagrant', group: 'vagrant'
  c.vm.provider :vmware_fusion do |p|
    p.gui = false
    p.vmx["memsize"] = "1024"
    p.vmx["numvcpus"] = "1"
  end
end
```

### Expected behavior

Shared folders should be mounted:

![gui_is_true](https://user-images.githubusercontent.com/1475276/143381534-398a946c-5310-4438-ba7b-1a16473478d3.png)

### Actual behavior

Shared folders are not mounted:

![gui_is_false](https://user-images.githubusercontent.com/1475276/143381550-69151cf7-89ca-41f9-a738-b9cbd0aa3d50.png)

### Steps to reproduce

Just change `gui` to `true/false` and `vagrant up`:
1. If `gui` is set to `false`, you'll need to open VMware Fusion, click `File`, click `Scan for Virtual Machines...` and scan the `.vagrant/machines/default/vmware_fusion/RANDOM_ID` directory so you can add the VM to GUI
2. If `gui` is set to `true`, the VM will appear directly in VMware Fusion as it'll be located in `/Users/$(whoami)/Virtual Machines`.

PS: I'm using kitchen-test but it should not matter as it just drives the `Vagrantfile` linked above.

Thanks in advance for looking into it!

**Comment by chrisroberts** [comment]
Hi there,

This issue should be resolved by [upgrading Vagrant](https://developer.hashicorp.com/vagrant/downloads) (with the latest release at this time being 2.3.5). If you still are encountering issues after upgrading, please open a new issue and I'll be happy to investigate further.

Cheers!
