### ISSUE TITLE
An error occurred while executing `vmrun`, a utility for controlling VMware machines.

### ISSUE THREAD

**Issue by Yuvraj-Takey** [hashicorp/vagrant-vmware-desktop#34]
Hello Team,

I am facing some issues after hitting the below command to boot vagrant instance

> `$ vagrant up --provider vmware_desktop`

**The error occurred is given below**

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start",
"/home/cdac/Downloads/.vagrant/machines/default/vmware_desktop/afab9169-c006-40a2-8795-0f75f3f8fbc9/ubuntu-18.04-amd64.vmx",
"nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: Error: The operation was canceled
Stderr:
```

I have followed the attached(file - [HashicorpGuide.txt](https://github.com/hashicorp/vagrant-vmware-desktop/files/7631356/HashicorpGuide.txt) click on link) installation instructions sent by Hashicorp team
earlier

We have tried all installation step several times with various utility-versions, but facing the same error message every time. Here are the experimented list
```
Ubuntu 18.04 --> VMWare 15.5.5 --> Vagrant 2.2.14 --> VagrantVMWare 1.0.17
Ubuntu 18.04 --> VMWare 15.5.5 --> Vagrant 2.2.16 --> VagrantVMWare 1.0.20
Ubuntu 18.04 --> VMWare 15.5.5 --> Vagrant 2.2.19 --> VagrantVMWare 1.0.21
Ubuntu 18.04 --> VMWare 15.5.2 --> Vagrant 2.2.19 --> VagrantVMWare 1.0.21
Ubuntu 20.04 --> VMWare 16.2.1 --> Vagrant 2.2.19 --> VagrantVMWare 1.0.21
Ubuntu 21.10 --> VMWare 16.2.1 --> Vagrant 2.2.19 --> VagrantVMWare 1.0.21
```

Please suggest some points to resolve the issue

**Comment by Yuvraj-Takey** [comment]
Hello Team,
The issue has been resolved. I was installing entire setup on Virtual Box machine (Version 6.1.26). Currently I have experimented on dedicated base system (Ubuntu 18.04, latest VMWare, latest Vagrant products).

Thank you 😊

**Comment by Yuvraj-Takey** [comment]
Can anyone please guide me, Why I was not able to install the entire setup on Virtual Box Machine  ?

Thank you

**Comment by Hollister009** [comment]
I have a similar issue but on mac: Apple M1 Chip

**Comment by ypicard** [comment]
Same here.

**Comment by philip-appinfotech** [comment]
Same here :

Apple M1 Chip
VMware Fusion 12.2.3
Vagrant 2.2.19

`An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "PATH_TO_VAGRANT_FOLDER/.vagrant/machines/default/vmware_desktop/0a34ebe7-fef1-442e-8246-a74a2c39d666/ubuntu-18.04-amd64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2022-06-16T15:42:58.202| ServiceImpl_Opener: PID 8429
Error: The operation was canceled

Stderr: 
`

**Comment by chrisroberts** [comment]
@Yuvraj-Takey Hi there, my apologies for the very delayed response to your question. The reason you were encountering that error is due to VirtualBox not having nested virtualization available (or disabled). This means that VMware is unable to run within the VirtualBox guest and any attempts to start a VMware backed virtual machine will fail as the virtual hardware will report that virtualization is not supported.

For everyone else commenting on the error with regards to macOS and apple silicon, please refer to #53 and [my comment here](https://github.com/hashicorp/vagrant-vmware-desktop/issues/53#issuecomment-1439291862)

Cheers!
