### ISSUE TITLE
Waiting for the VM to receive an address while DHCP is not running

### ISSUE THREAD

**Issue by Scorcher** [hashicorp/vagrant-vmware-desktop#37]
### Vagrant version

2.2.18 / 2.2.19

### Vagrant VMware plugin version

vagrant-vmware-desktop (3.0.1, global)

### Vagrant VMware utility version

1.0.21

### Host operating system

MacOS Monterey 12.2.1 (21D62) ARM
Darwin Kernel Version 21.3.0

### Guest operating system

ubuntu 20.04 (arm)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  # Ubuntu Server 20.04 (Focal Fossa) ARM64 Base Box https://github.com/BytesGuy/arm-base-boxes
  config.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "1"
  end
end
```

### Debug output

[vagrant.log (debug) and vagrant-vmware-utility.log (info)](https://gist.github.com/Scorcher/d200a4dc9e0f7c8de6af2d9b5cb7f972)

### Expected behavior

Vagrant box should start and obtain IP address.

### Actual behavior

Vagrant box started, but can't obtain IP address.

### Steps to reproduce

Usual case:
1. vagrant up
2. ... stuck on "Waiting for the VM to receive an address..."

Workaround case 1:
1. set `vm.gui = true` option in provider-specific configuration of vmware_desktop
2. vagrant up
3. success (vm is up)

Workaround case 2:
1. vagrant up
2. wait the state "Waiting for the VM to receive an address..."
3. start network services manually `sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --start`
4. success (vm is up)

### Additional notes

```bash
sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --status
```
while VMware Fusion.app or vmrun utility doesn't running returns:
```
DHCP service on vmnet1 is not running
Hostonly virtual adapter on vmnet1 is disabled
Hostonly virtual adapter on vmnet2 is disabled
DHCP service on vmnet8 is not running
NAT service on vmnet8 is not running
Hostonly virtual adapter on vmnet8 is disabled
Some/All of the configured services are not running
```

Looks like services (DHCP, NAT) can run after first VM is started and adapter assigned, because before that there is no any network bridge in host system.

**Comment by chrisroberts** [comment]
Hi there,

This issue should be resolved by [upgrading Vagrant](https://developer.hashicorp.com/vagrant/downloads) (with the latest release at this time being 2.3.5). If you still are encountering issues after upgrading, please open a new issue and I'll be happy to investigate further.

Cheers!

**Comment by phemmyog79** [comment]
I just upgraded my mac m2 to Sonoma 14. Now vagrant is stuck on  "Waiting for the VM to receive an address...". This is my Vagrantfile: 

Vagrant.configure("2") do |config| 
  config.vm.box = "spox/ubuntu-arm" 
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
   end
 end

pls help

**Comment by percygrunwald** [comment]
I was experiencing this issue as well, but I was able to resolve it by simply increasing the amount of memory the VM had from `512mb` to `768`.

```
    v.vmx["memsize"] = "768"
```

I tried destroying and recreating the VM many times at `512mb`, but it would always hang at `Waiting for the VM to receive an address...`:

```
$ vagrant up
Bringing machine 'ansible' up with 'vmware_desktop' provider...
==> ansible: Cloning VMware VM: 'bento/ubuntu-22.04-arm64'. This can take some time...
==> ansible: Checking if box 'bento/ubuntu-22.04-arm64' version '202306.30.0' is up to date...
==> ansible: Verifying vmnet devices are healthy...
==> ansible: Preparing network adapters...
==> ansible: Starting the VMware VM...
==> ansible: Waiting for the VM to receive an address...
```

With the following versions:

```
Mac OS 14.2.1
Vagrant 2.4.1
vagrant-vmware-desktop 3.0.3
Vagrant VMware Utility 1.0.22
```

And the following `Vagrantfile`:

```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04-arm64"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "512"
    v.vmx["numvcpus"] = 2
  end

  config.vm.define "ansible" do |m|
    m.vm.hostname = "ansible"
    m.vm.network "private_network", ip: "10.0.0.2"
  end
end
```

Additionally:

```
$ sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cli --status
DHCP service on vmnet1 is running
Hostonly virtual adapter on vmnet1 is disabled
Hostonly virtual adapter on vmnet2 is disabled
DHCP service on vmnet8 is running
NAT service on vmnet8 is running
Hostonly virtual adapter on vmnet8 is disabled
Some/All of the configured services are not running
```

By the process of elimination I worked out that the problem appeared to be the amount of memory assigned to the VM. This `Vagrantfile` worked consistently:

```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04-arm64"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "768"
    v.vmx["numvcpus"] = 2
  end

  config.vm.define "ansible" do |m|
    m.vm.hostname = "ansible"
    m.vm.network "private_network", ip: "10.0.0.2"
  end
end
```

Hope that helps anyone else experiencing this issue. Not sure why the memory affected it in this way, but presumably the VM simply wouldn't launch properly at such a low memory allocation. Would have been great to get a more detailed error message.
