### ISSUE TITLE
VMware vagrant issues n Windows with NFS mounts

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant-vmware-desktop#41]
Hi

We use a custom vagrant box on VMWare (using your Vagrant plugin/adapter) with NFS mounted host volumes into the VM.
Most of the team are Mac users, and after a few teething problems, things seem fine. Not so good on Windows.

Every time I start the VM with 'vagrant up', I have two problems:

1. NFS hangs on startup. It seems to be because the host IP it's trying to mount can't be resolved.
2. When I get past the NFS problem with the workaround below, I then find that the ports (e.g. 22 etc) are already in use.

I have to always run two workarounds before vagrant up.

To work around the NFS issue, I have to use the Virtual Network Editor in VMware and reset all virtual networks.
To work around the ports issue, I have to use Task Manager to restart all vmware services which are already running.

I've had this issue on various versions of VMWare and vagrant, under windows 10.

### Vagrant version

2.2.19

### Vagrant VMware plugin version

3.0.1

### Vagrant VMware utility version

1.0.21

### Host operating system

Windows 11

### Guest operating system

Ubuntu

### Vagrantfile

```


#########################################################################################
Vagrant.configure("2") do |config|
  # Networking and vagrant box
  config.vm.base_mac = nil
  config.vm.box = "secret/secret"
  config.vm.hostname = "xxxx"
  config.vm.box_version = "1.0.21"

  # Forwarded ports
  config.vm.network "forwarded_port",
    guest: 22,
    host: settings["ports"]["ssh"],
    id: "ssh",
    auto_correct: true

  config.vm.network "forwarded_port",
    guest: 3306,
    host: settings["ports"]["mysql"],
    id: "mysql"

  config.vm.network "forwarded_port",
    guest: 4431,
    host: settings["ports"]["4c-gateway"]['https'],
    id: "4c-gateway-https"

  config.vm.network "forwarded_port",
    guest: 4432,
    host: settings["ports"]["auth-service"]['https'],
    id: "auth-service-https"

  config.vm.network "forwarded_port",
    guest: 4433,
    host: settings["ports"]["4c-api"]['https'],
    id: "4c-api-https"

  config.vm.network "forwarded_port",
    guest: 4435,
    host: settings["ports"]["quote-service"]['https'],
    id: "quote-service-https"

  config.vm.network "forwarded_port",
    guest: 4436,
    host: settings["ports"]["document-generation-service"]['https'],
    id: "document-generation-service-https"

  # Set VMware provider settings
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.whitelist_verified = true
    vmware.gui = true
    vmware.vmx["memsize"] = settings['vmware_mem']
    vmware.vmx["numvcpus"] = settings['vmware_cpu']
  end

  # Windows specific
  if Vagrant::Util::Platform.windows? then
    # Install the windows NFS plugin if it's not installed
    unless Vagrant.has_plugin?("vagrant-winnfsd")
      puts 'Installing vagrant-winnfsd plugin...'
      system('vagrant plugin install vagrant-winnfsd')
    end

    # Map uid and guid
    config.winnfsd.uid = 1000
    config.winnfsd.gid = 1000
  end

  # Disable the default vagrant share to avoid performance overheads of sharing both NFS and native
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.synced_folder CODE_SRC, "/home/vagrant/src",
    type: "nfs",
    mount_options: NFS_MOUNT_OPTIONS,
    id: CODE_SRC,
    :map_uid => Process.uid,
    :map_gid => Process.gid

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Expected behavior
Should just work!

### Actual behavior

NFS hangs, ports are shown as already in use

### Steps to reproduce

As per description

**Comment by chrisroberts** [comment]
Closing as reporter account is no longer active
