### ISSUE TITLE
Enhancement Request: Apple Silicon build for vagrant-vmware-utility

### ISSUE THREAD

**Issue by fredngo** [hashicorp/vagrant-vmware-desktop#48]
**Is your feature request related to a problem? Please describe.**

* `vagrant-vmware-utility` is one of very few programs I have on my Apple Silicon Mac that still requires Rosetta

**Describe the solution you'd like**

* Universal binary build for both Intel and Apple Silicon 

**Describe alternatives you've considered**

* Not sure there's an alternative -- at some point there needs to be an `arm64` build

**Additional context**

* Attached screenshot:

<img width="699" alt="Screen Shot 2022-10-24 at 1 09 44 PM" src="https://user-images.githubusercontent.com/11791/197586487-a1a58877-5fcf-4342-91cb-dab0de4b454e.png">

**Comment by chrisroberts** [comment]
Hi there,

Included in #58 is an update for macOS utility builds to produce a universal binary. The next release will include the universal binary. Cheers!
