### ISSUE TITLE
Failed to locate the vmrest executable

### ISSUE THREAD

**Issue by manjufy** [hashicorp/vagrant-vmware-desktop#49]
I'm unable to run vagrant box with VMWare Fusion Tech. 

### Vagrant version

```
Vagrant 2.3.3
```

### Vagrant VMware plugin version

```
vagrant-vbguest (0.30.0, global)
vagrant-vmware-desktop (3.0.1, global)
```

### Vagrant VMware utility version

```
vagrant-vmware-utility -v
1.0.21
```

### Host operating system

```
Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
```

### Guest operating system

```
debian/buster64
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/buster64"
  config.vm.hostname = "devbox-01"
  config.vm.define "devbox-01"
  config.vagrant.plugins = ['vagrant-vbguest']

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./", "/home/vagrant/project"

  config.vm.provider "vmware_desktop" do |vd|
    vd.cpus = 4
    vd.memory = "2048"
    vd.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl git cmake tmux vim  # ...
  SHELL

  config.vm.provision "docker" do |d|
    d.run "nginx"
  end
```

### Debug output

Here is the sample log details from `vagrant-vimware-utility/service.log`

```
Halting the Vagrant VMware API service
2022-11-18T01:28:40.769+0100 [INFO]  vagrant-vmware-utility.api: created: vmx=<nil>
2022-11-18T01:28:40.848+0100 [INFO]  vagrant-vmware-utility.api: attempting to upgrade to vmrest driver
2022-11-18T01:28:40.848+0100 [WARN]  vagrant-vmware-utility.api.vmrest: failed to create vmrest driver: error="Failed to locate the vmrest executable"
2022-11-18T01:28:40.848+0100 [INFO]  vagrant-vmware-utility.api.vmrest: using fallback driver
2022-11-18T01:28:40.848+0100 [INFO]  vagrant-vmware-utility.api: enabling internal port forwarding service
Starting the Vagrant VMware API service
2022-11-18T01:28:41.269+0100 [INFO]  vagrant-vmware-utility.api.api: api service start: host=127.0.0.1 port=9999
```

### Expected behavior

What should have happened?

### Actual behavior

What actually happened?

### Steps to reproduce

Some of the steps I have followed are from the Stackoverflow thread https://stackoverflow.com/questions/72112571/vagrant-vmware-utility-driver

### References

https://stackoverflow.com/questions/72112571/vagrant-vmware-utility-driver

https://github.com/hashicorp/vagrant-vmware-desktop/issues/22

**Comment by chrisroberts** [comment]
Hi there,

Providing the full output in a gist of `vagrant up --debug` will be helpful in confirming the underlying issue you are encountering. If you are using fusion player, and not fusion pro, the vmrest functionality will not be available.

**Comment by mikeroySoft** [comment]
This is almost certainly because the Fusion "Tech Preview" is in a different path than Fusion "GA". 
When I was testing during our lead up before we released Fusion 13, I simply renamed the .app from 'VMware Fusion Tech Preview.app' to 'VMware Fusion.app' and it worked as expected.

Recommend using Fusion 13 instead of the Tech Preview now that it's been released. The TP probably doesn't even work anymore, as I think the license key expired.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant-vmware-desktop/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
