### ISSUE TITLE
after update vagrant-vmware-desktop to v3.0.2, vagrant became ill

### ISSUE THREAD

**Issue by work-chausat** [hashicorp/vagrant-vmware-desktop#78]
i use vmware fusion 13.0.2 (21581413) on mac, after update to v3.0.2, each comand always got error:

An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "list", {:notify=>[:stdout, :stderr]}]

Stdout: Invalid host type 'player' specified
Error: The operation is not supported

so, i changed the code: https://github.com/hashicorp/vagrant-vmware-desktop/blob/main/lib/vagrant-vmware-desktop/driver/base.rb, change 190-192:
from:

          if standard?
            return @product_type = "player"
          end

to:

          if standard?
            return @product_type = "fusion"
          end

after this, error disappeared.

**Comment by chrisroberts** [comment]
@work-chausat Thank you for the report! I will release the updated plugin with this fix later today. Cheers!
