### ISSUE TITLE
Vagrant up not responding 

### ISSUE THREAD

**Issue by Trezy1** [hashicorp/vagrant-vmware-desktop#82]
Please note that the Vagrant VMware plugin issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

My vagrant version is : Vagrant 2.3.4

### Vagrant VMware plugin version

Run `vagrant plugin list` to show the version. If you are not running the latest
version of the Vagrant VMware plugin, please upgrade before submitting an issue.

Plugin version: vagrant-hostmanager (1.8.9, global)
vagrant-vmware-desktop (3.0.2, global)

### Vagrant VMware utility version

To show the version, run `C:\HashiCorp\vagrant-vmware-desktop\bin\vagrant-vmware-utility -v` on
Windows systems or `/opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility -v` on non-Windows
systems. If you are not running the latest version of the Vagrant VMware utility, please
upgrade before submitting an issue.

My version is : 1.0.21

### Host operating system

This is the operating system that you run locally.

Mac ,,, chip M1

### Guest operating system

This is the operating system you run in the virtual machine.

Ubuntu 

### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)

Vagrant.configure("2") do |config|
              config.vm.box = "spox/ubuntu-arm"
              config.vm.box_version = "1.0.0"
              config.vm.network "private_network" , ip: "192.168.56.11"
              config.vm.provider "vmware_desktop" do |vmware| 
                vmware.gui = true
                vmware.allowlist_verified = true
           end
end 

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

<script src="https://gist.github.com/Trezy1/a5aeedd5f94897985a0113d087ad4ee3.js"></script>

### Expected behavior

What should have happened?

It shoukd started the Vitual machine 

### Actual behavior

What actually happened?

not starting at all 

### Steps to reproduce

1. Install rosetta 
2. install vagrant with homebrew
3. create an account in vmware
4. install vm fusion tech preview 
5. create a link: 
![image](https://user-images.githubusercontent.com/96459570/236630139-abec0929-8138-4c45-94e5-25022f0c3ec2.png)
6. install vagrant utility
7. install vagrant plugin 
8. create a Vagrantfile with the content above
9.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by EnorMOZ** [comment]
Looks like you initialized you  project with `vagrant init` and ran `vagrant up` directly.
Make sure you run your `vagrant up` command in the same directory you have your edited Vagrantfile in.

**Comment by Trezy1** [comment]
I have deleted everything and run vagrant up,, I want to send a screen shot, how could I do that ??

**Comment by chrisroberts** [comment]
Hi there,

With the release of VMware Fusion 13 the tech preview is no longer supported and some functionality will be broken. With VMware Fusion 13 installed, you can follow [this guide](https://developer.hashicorp.com/vagrant/tutorials/getting-started/getting-started-project-setup) for getting a project setup. Just replace the `hashicorp/bionic64` box name used with `spox/ubuntu-arm`. After you are able to properly run a `vagrant up` to bring the guest up, you can modify the Vagrantfile to include any adjustments you may want.

Cheers!
