### ISSUE TITLE
VMWare plugin cannot communicate with vagrant

### ISSUE THREAD

**Issue by shade477** [hashicorp/vagrant-vmware-desktop#99]
I am trying to create a new box of ubuntu server on a windows host. I am getting this error message when I am starting the box. I have generated the certificates for the plugins.
### VMWare workstation version
17.0.2 build-21581411

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "rkrause/ubuntu-21.10-arm64"
  config.vm.box_version = "1.0.0"
end
```
### Error message

~> vagrant up
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please open a new issue at:

  https://github.com/hashicorp/vagrant-vmware-desktop/issues

**Comment by atchaikovski** [comment]
Hello there. 
any movement on this? have a similar message but with vCenter, utility versions tried 1.0.22, 1.0.19. 
thank you!

**Comment by chrisroberts** [comment]
Hi there,

Based on the error message it appears that you may not have the vagrant vmware utility installed which is required for using the vagrant vmware plugin. Please try [installing the vagrant-vmware-utility](https://developer.hashicorp.com/vagrant/docs/providers/vmware/vagrant-vmware-utility) to verify if the error message you are receiving still exists.

The box you are attempting to use is based on ARM64 architecture, however, and will not work on your Windows system. You'll need to use an amd64 based box for proper compatibility.

Cheers.

**Comment by shade477** [comment]
Hi all,
Thanks for all the help. The issue has been resolved. I found out that the vmware plugin was installed but not enabled. I enabled it and it seemed to fix the issue. I am using a windows host so I also needed to uninstall its optional feature openssh for it to work as expected.
